start_poll: 12
score: 9 
score_width: 12.0
colls:
  - source: 2
    target: 1
    width: 20.0
  - source: 3
    target: 2
    width: 20.0
  - source: 4
    target: 3
    width: 15.0
  - source: 5
    target: 4
    width: 25.0
  - source: 6
    target: 5
    width: 20.0
  - source: 7
    target: 6
    width: 20.0
  - source: 8
    target: 7
  - source: 9
    target: 8
    width: 15.0