start_poll: L
score: E
score_width: 12.0
colls:
  - source: C
    target: A
    width: 20.0
  - source: D
    target: B
    width: 15.0
  - source: E
    target: C
    width: 25.0
  - source: G
    target: D
    width: 20.0